"""empty message

Revision ID: 7f8ee96fb5fa
Revises: b6c070ecb39d
Create Date: 2024-09-29 14:24:37.108988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8ee96fb5fa'
down_revision = 'b6c070ecb39d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verif', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')
        batch_op.drop_column('is_verif')

    # ### end Alembic commands ###
