"""empty message

Revision ID: b6c070ecb39d
Revises: d63268430a9b
Create Date: 2024-09-29 14:03:20.887466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6c070ecb39d'
down_revision = 'd63268430a9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('short_bio', sa.Text(), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               nullable=True)
        batch_op.drop_column('short_bio')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
