"""empty message

Revision ID: d2367222c3cd
Revises: 41aa5bea1d83
Create Date: 2024-09-29 22:10:58.929493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2367222c3cd'
down_revision = '41aa5bea1d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viewed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('like', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('like')
        batch_op.drop_column('viewed')

    # ### end Alembic commands ###
